module.exports = {
  docs: [
    'index',
    'suite-format',
    'local-development',
    'docker',
    'static-publishing',
    { type: 'category', label: 'CLI reference', items: [{ type: 'autogenerated', dirName: 'cli' }] },
  ],
};
